clear all; close all; clc;

nmbrOfParticles = 2;

FPS = 30;
simulationTime = 20; %seconds
frames = simulationTime * FPS;

particle = struct(...
    'density', 0, ...
    'position',[0 0], ...
    'velocity',[0 0], ...
    'pressure',0, ...
    'force',[0 0], ...
    'cs', 0);

parameters = struct(...
 'dt', 1 / FPS, ...
    'mass',1, ...
    'kernelSize',1, ...
    'gasConstantK',0.2, ...
    'viscosityConstant', 70, ...
    'restDensity', 4, ...
    'sigma', 72e-3, ...
    'nThreshold', 0.02, ...
    'gravity', [0 -9.82], ...
    'leftBound', 0, ...
    'rightBound', 2, ...
    'bottomBound', 0, ...
    'topBound', 5, ...
    'wallDamper', 0.0006);

% parameters.leftBound+0.5*rand, parameters.topBound-0.5*rand

%% Several Particles

    for idx = 1:40;
        particles(idx) = particle;
        particles(idx).position = [parameters.leftBound+0.5*rand, parameters.topBound-0.5*rand];
        particles(idx).velocity = [0 0];
        particles(idx).density = 1400;

    end
    grid on;
    figure;
while true
    particles = calculateForces(particles, parameters);
    particles = performTimestep(particles, parameters.dt);
    particles = checkBoundaries(particles, parameters);
    clf;
    grid on;
    hold on;
    drawParticles(particles);
    axis([(parameters.leftBound-1) (parameters.rightBound+1) (parameters.bottomBound-1) (parameters.topBound+1)]);
    pause(0.0001);
end